// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.beehivecoll;

import com.beehivecoll.Circle;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Circle_Roo_Configurable {
    
    declare @type: Circle: @Configurable;
    
}
